

const products = [
  {
    id: 1,
    name: "Adidas CoreFit T-Shirt",
    category: "Men",
    shortDescription: "A comfortable and lightweight classic.",
    description: "Experience the perfect blend of comfort and performance with the CoreFit T-Shirt. Made with breathable, moisture-wicking fabric. Ideal for workouts or everyday casual wear.",
    price: 3500,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "Purple", "Green"],
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 2,
    name: "Nike Dri-FIT Running Shorts",
    category: "Men",
    shortDescription: "Stay dry and focused on your run.",
    description: "Lightweight running shorts featuring Nike Dri-FIT technology to move sweat away from your skin. Includes an internal key pocket and an elastic waistband with drawcord.",
    price: 2800,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Red", "Blue"],
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 3,
    name: "Puma Training Hoodie",
    category: "Women",
    shortDescription: "Warm and cozy for your post-workout cool down.",
    description: "A soft fleece training hoodie with an adjustable drawstring hood and a kangaroo pocket. Perfect for layering during colder months or for lounging.",
    price: 5500,
    sizes: ["M", "L", "XL"],
    colors: ["Navy", "Charcoal", "Olive"],
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 4,
    name: "Under Armour Leggings",
    category: "Women",
    shortDescription: "Support and recovery for peak performance.",
    description: "These leggings offer serious compression to aid muscle recovery. Four-way stretch construction moves better in every direction. Great for high-intensity training.",
    price: 4200,
    sizes: ["S", "M", "L"],
    colors: ["Black", "White"],
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 5,
    name: "Reebok Classic Sneakers",
    category: "Shoes",
    shortDescription: "Timeless style and everyday comfort.",
    description: "The iconic Reebok Classic Leather shoe with a soft garment leather upper and a lightweight cushioned midsole. A perfect retro-inspired look for your everyday casual style.",
    price: 8500,
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["White", "Black"],
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 6,
    name: "New Balance 990v5",
    category: "Shoes",
    shortDescription: "Premium running shoe built for stability.",
    description: "A heritage running shoe known for its superior comfort, durability, and support. Features a pigskin/mesh upper and ENCAP midsole technology.",
    price: 18500,
    sizes: ["41", "42", "43", "44"],
    colors: ["Grey", "Black", "Navy"],
    image: "https://images.unsplash.com/photo-1551107643-51335540a33a?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 7,
    name: "The North Face Resolve",
    category: "Kids",
    shortDescription: "Waterproof and breathable protection.",
    description: "A lightweight, packable jacket for rain protection on the trail. Features DryVent™ technology, a fully adjustable hood, and elastic cuffs.",
    price: 7500,
    sizes: ["S", "M", "L"],
    colors: ["Yellow", "Red", "Black"],
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 8,
    name: "Columbia Hiking Pants",
    category: "Men",
    shortDescription: "Two-in-one outdoor versatility.",
    description: "These pants easily convert to shorts via zippered legs. Made with Omni-Shade™ UPF 50 sun protection fabric. Perfect for hiking and variable weather.",
    price: 4800,
    sizes: ["30", "32", "34", "36"],
    colors: ["Fossil", "Sage"],
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 9,
    name: "Patagonia Fleece Vest",
    category: "Men",
    shortDescription: "Warm, low-bulk vest for layering.",
    description: "A warm, midweight polyester fleece vest made of 100% recycled material. Features a full-zip front and two zippered handwarmer pockets.",
    price: 9500,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Oatmeal", "Nickel"],
    image: "https://images.unsplash.com/photo-1626073711623-6688f98c7155?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 10,
    name: "Under Armour Backpack",
    category: "Accessories",
    shortDescription: "Durable and water-resistant storage.",
    description: "Features UA Storm technology for a water-resistant finish and padded laptop sleeve.",
    price: 4500,
    sizes: ["One-Size"],
    colors: ["Black", "Camo"],
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800",
  }
];

export default products;